Centos7 disable
sclorg/redis-container pull request #148
Opened 2023-07-18 12:05 UTC by zmiklank

2023-07-18 12:06 UTC, zmiklank commented
[test-all]

2023-07-19 12:47 UTC, phracek requested changes
Only one thing. The latest tag should be still present in redis-centos.json file.

Please update also main README.md file and mark CentOS 7 as deprecated or delete it.

2023-07-19 12:47 UTC, phracek commented on imagestreams/redis-centos.json
> -        "name": "latest"
The latest part should be there and changed to something that is still supported. like 6-el8.

2023-07-19 12:47 UTC, phracek commented on imagestreams/redis-centos.json
> -          "name": "5-el8"
`6-el8` should be marked as 'latests'

2023-07-19 13:02 UTC, zmiklank commented
> Only one thing. The latest tag should be still present in redis-centos.json file.

This is now updated. Can you recheck?

> Please update also main README.md file and mark CentOS 7 as deprecated or delete it.

THank for catching this. I have updated readme for redis 7. As for other readmes; this PR is based on the nginx one (https://github.com/sclorg/nginx-container/pull/256). The READMEs should be kept as they are, as we still have the centos7 images available on quay.io. We will just stop doing their updates and rebuilds.

2023-07-19 13:08 UTC, phracek requested changes
Only two nitpicks. CentOS 7 is mentioned in main README.md file still as an available image on quay.io

And CentOS 7 is mentioned as supported in the list of supported versions.
I would also prefer in example on main README.md file to replace CentOS 7 with CentOS Stream 8.

2023-07-19 13:17 UTC, zmiklank commented
> Only one nitpicks.
> 
> And CentOS 7 is mentioned as supported in the list of supported versions. I would also prefer in example on main README.md file to replace CentOS 7 with CentOS Stream 8.

@pkubatrh, could you please share you opinion on this?

2023-07-24 11:02 UTC, phracek commented
> 

Like @pkubatrh mentioned in nginx-container. Let's keep it.

2023-07-24 11:04 UTC, phracek approved these changes

2023-07-24 12:18 UTC, phracek commented
[test-all]

2023-07-24 14:20 UTC, merged