Fixes: #128 Add support for adding bind to /etc/redis.conf
sclorg/redis-container pull request #153
Opened 2023-08-28 13:59 UTC by phracek

Add support for adding bind to /etc/redis.conf
by BIND_ADDRESS variable

Closes #128

2023-08-29 07:21 UTC, phracek commented
[test]

2023-08-29 07:34 UTC, phracek commented
[test]

2023-08-29 10:32 UTC, phracek commented
[test]

2023-08-29 11:31 UTC, phracek commented
[test-openshift]

2023-08-29 11:49 UTC, phracek commented
@yrro @pkubatrh @hhorak @zmiklank Please review it.

2023-08-29 12:28 UTC, yrro requested changes
LGTM thanks, just spotted a typo

2023-08-29 12:28 UTC, yrro commented on 6/root/usr/share/container-scripts/redis/README.md
> +       Configuration redis to listen on this address
Typo - `Configuration` -> `Configure`

2023-08-29 12:30 UTC, yrro requested changes

2023-08-29 12:30 UTC, yrro commented on 7/root/usr/share/container-scripts/redis/README.md
> +       Configuration redis to listen on this address
Oh, the typo is here too. Actaully it would be more consistent with the other environment variable descriptions if the text was something like "IP address for the server to listen on".

2023-08-30 10:08 UTC, phracek commented on 7/root/usr/share/container-scripts/redis/README.md
> +       Configuration redis to listen on this address
Fixed by https://github.com/sclorg/redis-container/pull/153/commits/8668c141a066d647df6597a41db1c3f710141ec4

2023-08-30 10:08 UTC, phracek commented on 6/root/usr/share/container-scripts/redis/README.md
> +       Configuration redis to listen on this address
Fixed by https://github.com/sclorg/redis-container/pull/153/commits/8668c141a066d647df6597a41db1c3f710141ec4

2023-08-30 10:08 UTC, phracek commented
[test]

2023-09-07 08:58 UTC, merged